### ISSUE TITLE
Compositing

### ISSUE THREAD

**Issue by ghost** [BurntSushi/wingo#119]
Compositing simply does not work. There are big black boxes where the windows should be transparent.
Some pictures are here: http://imgur.com/a/bUjvu

**Comment by Happy-Ferret** [comment]
Any solution to the above problem? I'd appreciate being able to use rounded corners.

**Comment by BurntSushi** [comment]
Compositing has been working just fine for me with Wingo for the past several years. Therefore, I won't be looking into this bug. You're on your own.

**Comment by Happy-Ferret** [comment]
Would you, at the very least, know if/how I may exclude a window from being managed/decorated by ``wingo``? I tried _NET_WM_STATE_DOCK but that wasn't enough in this particular instance.

**Comment by BurntSushi** [comment]
Wingo follows EWMH. I use dzen2, trayer and gkrellm successfully.

**Comment by Happy-Ferret** [comment]
I've seen that.

In the case of my particular application that's still not enough. XUL popups do not adhere to _NET_WM state hints.

I've already tried disabling frame borders but that didn't fix it either.

Shame the OP no longer seems to be on Github. He seemed to know what the issue is/how to fix it.

**Comment by Happy-Ferret** [comment]
The issue isn't necessarily related to compositing, btw.

Without a window manager and without a compositor, the window of my application is rendered with rounded corners. As soon as I launch ``wingo``, the window changes to a square shape. The back-face of the window is now also completely square.

**Comment by BurntSushi** [comment]
Dunno. Sorry.
