### ISSUE TITLE
[question] Possible Bug on Sleep

### ISSUE THREAD

**Issue by whereswaldon** [BurntSushi/wingo#131]
Sometimes when I close my laptop with Wingo running, it fails to sleep properly. Instead, everything freezes and I can't seem to find any errors in a log (or in wingo's output). I don't know whether this is actually wingo's fault, but I did want to ask:
1 - Has wingo been used/tested extensively on laptops?
2 - Do you have any suggestions about how to diagnose this? Is there a solid way for me to determine whether it is/n't wingo's fault?

**Comment by BurntSushi** [comment]
I've used Wingo on my laptop for the last several years. Sleep works fine. I don't know how Wingo would impact sleep.

**Comment by whereswaldon** [comment]
Okay, the issue is likely somewhere else then. Thanks!
