### ISSUE TITLE
Vulkan?

### ISSUE THREAD

**Issue by rucuriousyet** [BurntSushi/wingo#135]
I wonder if you could use something like vulkan-go to do hardware compositing with Go? I will have to do some research here but it could be a decently viable option (if you don't mind the very low level API that is Vulkan)

**Comment by BurntSushi** [comment]
You can wonder all you like, but you'll need to do it on your own time.

Your request is basically "I wonder if you could rewrite Wingo" which is pretty unreasonable.

**Comment by rucuriousyet** [comment]
No, I was just hoping for some insight as this seems to be your area of
expertise and I'm just getting into it... Sorry for the confusion.

-sent from my OnePlus X

On Oct 23, 2017 5:38 AM, "Andrew Gallant" <notifications@github.com> wrote:

You can wonder all you like, but you'll need to do it on your own time.

Your request is basically "I wonder if you could rewrite Wingo" which is
pretty unreasonable.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/BurntSushi/wingo/issues/135#issuecomment-338603830>,
or mute
the thread

**Comment by BurntSushi** [comment]
No worries. But it is not my area of expertise. Wingo isn't a compositor.
