### ISSUE TITLE
How to change keyboard map?

### ISSUE THREAD

**Issue by lorico** [BurntSushi/wingo#136]
Hello,
Thanks for this nice project!
For some reason, when I startx with wingo, it doesn't apply the keyboard mapping set on my arch system:
if I run localectl, I can see the "VC Keymap" is correct, but when I type I still get an US keyboard....
also, command:
loadkeys fr-pc
gives: "couldn't get a file descriptor referring to the console"...
=> So how could I change the keyboard mapping please ? Any tip ?

**Comment by BurntSushi** [comment]
I don't know. This might not be possible. Sorry.

**Comment by lorico** [comment]
ok thanks for the answer !
