### ISSUE TITLE
Possible to maximize a tiled window directly?

### ISSUE THREAD

**Issue by jsbmg** [BurntSushi/wingo#146]
This is not a feature request, just a question - is it possible to maximize a tiled window? Currently, I either float the window, then maximize it, or cycle through the layouts until I get to the "Monocle" layout. Is there a more direct way to switch a tiled window to fullscreen I should be using? 

If it's not possible, no worries and I'll close this issue. I know active development has stopped long ago on this, but it's truly a gem of a window manager and I'll continue to use it regardless.

**Comment by BurntSushi** [comment]
I think I would just bind a key to `SetLayout (GetWorkspace) "Maximized"`.

**Comment by BurntSushi** [comment]
> I know active development has stopped long ago on this, but it's truly a gem of a window manager and I'll continue to use it regardless.

Thanks. :-) And yeah, I still use it daily on all my machines. It is basically "done" from my perspective.

**Comment by jsbmg** [comment]
Thanks!
